import type { NutrientDescription } from "./types"

export function getNutrientsDescription(): NutrientDescription[] {
  const nutrientDescription: NutrientDescription[] = [
    {
      name: "Stikstof, werkzaam",
      symbol: "N",
      type: "primary",
      unit: "kg N/ha",
      adviceParameter: "d_n_req",
      doseParameter: "p_dose_nw",
    },
    {
      name: "Fosfaat",
      symbol: "P",
      type: "primary",
      unit: "kg P2O5/ha",
      adviceParameter: "d_p_req",
      doseParameter: "p_dose_p",
    },
    {
      name: "Kalium",
      symbol: "K",
      type: "primary",
      unit: "kg K2O/ha",
      adviceParameter: "d_k_req",
      doseParameter: "p_dose_k",
    },
    {
      name: "Organische koolstof",
      symbol: "EOC",
      type: "secondary",
      unit: "kg EOC/ha",
      adviceParameter: "d_c_req",
      doseParameter: "p_dose_eoc",
    },
    {
      name: "Zwavel",
      symbol: "S",
      type: "secondary",
      unit: "kg S/ha",
      adviceParameter: "d_s_req",
      doseParameter: "p_dose_s",
    },
    {
      name: "Magnesium",
      symbol: "Mg",
      type: "secondary",
      unit: "kg MgO/ha",
      adviceParameter: "d_mg_req",
      doseParameter: "p_dose_mg",
    },
    {
      name: "Calcium",
      symbol: "Ca",
      type: "secondary",
      unit: "kg CaO/ha",
      adviceParameter: "d_ca_req",
      doseParameter: "p_dose_ca",
    },
    {
      name: "Natrium",
      symbol: "Na",
      type: "secondary",
      unit: "kg Na/ha",
      adviceParameter: "d_na_req",
      doseParameter: "p_dose_na",
    },
    {
      name: "Koper",
      symbol: "Cu",
      type: "trace",
      unit: "kg Cu/ha",
      adviceParameter: "d_cu_req",
      doseParameter: "p_dose_cu",
    },
    {
      name: "Zink",
      symbol: "Zn",
      type: "trace",
      unit: "kg Zn/ha",
      adviceParameter: "d_zn_req",
      doseParameter: "p_dose_zn",
    },
    {
      name: "Kobalt",
      symbol: "Co",
      type: "trace",
      unit: "kg Co/ha",
      adviceParameter: "d_co_req",
      doseParameter: "p_dose_co",
    },
    {
      name: "Mangaan",
      symbol: "Mn",
      type: "trace",
      unit: "kg Mn/ha",
      adviceParameter: "d_mn_req",
      doseParameter: "p_dose_mn",
    },
    {
      name: "Molybdenum",
      symbol: "Mo",
      type: "trace",
      unit: "kg Mo/ha",
      adviceParameter: "d_mo_req",
      doseParameter: "p_dose_mo",
    },
    {
      name: "Boor",
      symbol: "B",
      type: "trace",
      unit: "kg B/ha",
      adviceParameter: "d_b_req",
      doseParameter: "p_dose_b",
    },
  ]
  return nutrientDescription
}
