/**
 * Sidebar configuration for the auto-generated API reference documentation.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsApi = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // For the API reference, we want it to auto-generate from the 'api-reference' directory
  apiSidebar: [{ type: "autogenerated", dirName: "." }],
}

module.exports = sidebarsApi
