export const nitrogenStandardsData = [
    {
        cultivation_rvo_table2: "Grasland",
        b_lu_catalogue_match: ["nl_265", "nl_331"],
        type: "grasland",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "beweiden",
                norms: {
                    klei: { standard: 345, nv_area: 276 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 250, nv_area: 200 },
                    loess: { standard: 250, nv_area: 200 },
                    veen: { standard: 265, nv_area: 212 },
                },
            },
            {
                omschrijving: "volledig maaien",
                norms: {
                    klei: { standard: 385, nv_area: 308 },
                    zand_nwc: { standard: 320, nv_area: 256 },
                    zand_zuid: { standard: 320, nv_area: 256 },
                    loess: { standard: 320, nv_area: 256 },
                    veen: { standard: 300, nv_area: 240 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Tijdelijk grasland",
        b_lu_catalogue_match: ["nl_266"],
        type: "grasland_tijdelijk",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                period_description: "van 1 januari tot minstens 15 april",
                period_start_month: 1,
                period_start_day: 1,
                period_end_month: 4,
                period_end_day: 15,
                norms: {
                    klei: { standard: 60, nv_area: 48 },
                    zand_nwc: { standard: 50, nv_area: 40 },
                    zand_zuid: { standard: 50, nv_area: 40 },
                    loess: { standard: 50, nv_area: 40 },
                    veen: { standard: 50, nv_area: 40 },
                },
            },
            {
                period_description: "van 1 januari tot minstens 15 mei",
                period_start_month: 1,
                period_start_day: 1,
                period_end_month: 5,
                period_end_day: 15,
                norms: {
                    klei: { standard: 110, nv_area: 88 },
                    zand_nwc: { standard: 90, nv_area: 72 },
                    zand_zuid: { standard: 90, nv_area: 72 },
                    loess: { standard: 90, nv_area: 72 },
                    veen: { standard: 90, nv_area: 72 },
                },
            },
            {
                period_description: "van 1 januari tot minstens 15 augustus",
                period_start_month: 1,
                period_start_day: 1,
                period_end_month: 8,
                period_end_day: 15,
                norms: {
                    klei: { standard: 250, nv_area: 200 },
                    zand_nwc: { standard: 210, nv_area: 168 },
                    zand_zuid: { standard: 210, nv_area: 168 },
                    loess: { standard: 210, nv_area: 168 },
                    veen: { standard: 210, nv_area: 168 },
                },
            },
            {
                period_description: "van 1 januari tot minstens 15 september",
                period_start_month: 1,
                period_start_day: 1,
                period_end_month: 9,
                period_end_day: 15,
                norms: {
                    klei: { standard: 280, nv_area: 224 },
                    zand_nwc: { standard: 235, nv_area: 188 },
                    zand_zuid: { standard: 235, nv_area: 188 },
                    loess: { standard: 235, nv_area: 188 },
                    veen: { standard: 235, nv_area: 188 },
                },
            },
            {
                period_description: "van 1 januari tot minstens 15 oktober",
                period_start_month: 1,
                period_start_day: 1,
                period_end_month: 10,
                period_end_day: 15,
                norms: {
                    klei: { standard: 310, nv_area: 248 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 250, nv_area: 200 },
                    loess: { standard: 250, nv_area: 200 },
                    veen: { standard: 265, nv_area: 212 },
                },
            },
            {
                period_description: "vanaf 15 april tot minstens 15 oktober",
                period_start_month: 4,
                period_start_day: 15,
                period_end_month: 10,
                period_end_day: 15,
                norms: {
                    klei: { standard: 310, nv_area: 248 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 250, nv_area: 200 },
                    loess: { standard: 250, nv_area: 200 },
                    veen: { standard: 265, nv_area: 212 },
                },
            },
            {
                period_description: "vanaf 15 mei tot minstens 15 oktober",
                period_start_month: 5,
                period_start_day: 15,
                period_end_month: 10,
                period_end_day: 15,
                norms: {
                    klei: { standard: 280, nv_area: 224 },
                    zand_nwc: { standard: 235, nv_area: 188 },
                    zand_zuid: { standard: 235, nv_area: 188 },
                    loess: { standard: 235, nv_area: 188 },
                    veen: { standard: 235, nv_area: 188 },
                },
            },
            {
                period_description: "vanaf 15 augustus tot minstens 15 oktober",
                period_start_month: 8,
                period_start_day: 15,
                period_end_month: 10,
                period_end_day: 15,
                norms: {
                    klei: { standard: 95, nv_area: 76 },
                    zand_nwc: { standard: 80, nv_area: 64 },
                    zand_zuid: { standard: 80, nv_area: 64 },
                    loess: { standard: 80, nv_area: 64 },
                    veen: { standard: 80, nv_area: 64 },
                },
            },
            {
                period_description:
                    "vanaf 15 september tot minstens 15 oktober",
                period_start_month: 9,
                period_start_day: 15,
                period_end_month: 10,
                period_end_day: 15,
                norms: {
                    klei: { standard: 30, nv_area: 24 },
                    zand_nwc: { standard: 25, nv_area: 20 },
                    zand_zuid: { standard: 25, nv_area: 20 },
                    loess: { standard: 25, nv_area: 20 },
                    veen: { standard: 25, nv_area: 20 },
                },
            },
            {
                period_description: "vanaf 15 oktober",
                period_start_month: 10,
                period_start_day: 15,
                period_end_month: 12,
                period_end_day: 31,
                norms: {
                    klei: { standard: 0, nv_area: 0 },
                    zand_nwc: { standard: 0, nv_area: 0 },
                    zand_zuid: { standard: 0, nv_area: 0 },
                    loess: { standard: 0, nv_area: 0 },
                    veen: { standard: 0, nv_area: 0 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewas, consumptie aardappelen",
        b_lu_catalogue_match: ["nl_2014"],
        type: "aardappel",
        is_winterteelt: false,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "hoge norm",
                varieties: [
                    "Adora",
                    "Annabelle",
                    "Bintje",
                    "Carlita",
                    "Courage",
                    "Draga",
                    "Felsina",
                    "Fontane",
                    "Innovator",
                    "Inova",
                    "Jaerla",
                    "Lady Blanca",
                    "Lady Olympia",
                    "Lady Rosetta",
                    "Liseta",
                    "Maritiema",
                    "Marlen",
                    "Miranda",
                    "Ramos",
                    "Redstar",
                    "Sante",
                    "Satellite",
                    "Victoria",
                    "VR 808",
                    "Zorba",
                ],
                norms: {
                    klei: { standard: 275, nv_area: 220 },
                    zand_nwc: { standard: 260, nv_area: 208 },
                    zand_zuid: { standard: 208, nv_area: 166 },
                    loess: { standard: 204, nv_area: 163 },
                    veen: { standard: 270, nv_area: 216 },
                },
            },
            {
                omschrijving: "lage norm",
                varieties: [
                    "Agria",
                    "Allure",
                    "Alpha",
                    "Aprilia",
                    "Asterix",
                    "Aziza",
                    "Ballys",
                    "Baraka",
                    "Bartina",
                    "Ceasar",
                    "Dore",
                    "Eigenheimer",
                    "El Paso",
                    "Futura",
                    "Gloria",
                    "Irene",
                    "Maradonna",
                    "Markies",
                    "Milva",
                    "Minerva",
                    "Mondial",
                    "Morene",
                    "Mozart",
                    "Producent",
                    "Remarka",
                    "Rodeo",
                    "Safari",
                    "Saphire",
                    "Simply Red",
                    "Spirit",
                    "Terra Gold",
                    "Ukama",
                    "Vision",
                ],
                norms: {
                    klei: { standard: 225, nv_area: 180 },
                    zand_nwc: { standard: 210, nv_area: 168 },
                    zand_zuid: { standard: 168, nv_area: 134 },
                    loess: { standard: 164, nv_area: 131 },
                    veen: { standard: 220, nv_area: 176 },
                },
            },
            {
                omschrijving: "overig",
                norms: {
                    klei: { standard: 250, nv_area: 200 },
                    zand_nwc: { standard: 235, nv_area: 188 },
                    zand_zuid: { standard: 188, nv_area: 150 },
                    loess: { standard: 184, nv_area: 147 },
                    veen: { standard: 245, nv_area: 196 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2:
            "Consumptieaardappel, vroeg (loofvernietiging voor 15 juli)",
        b_lu_catalogue_match: ["nl_1911", "nl_1912"],
        type: "aardappel",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 120, nv_area: 96 },
            zand_nwc: { standard: 120, nv_area: 96 },
            zand_zuid: { standard: 96, nv_area: 77 },
            loess: { standard: 96, nv_area: 77 },
            veen: { standard: 120, nv_area: 96 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewas, pootaardappelen",
        b_lu_catalogue_match: ["nl_2015", "nl_2016"],
        type: "aardappel",
        is_winterteelt: false,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "hoge norm",
                varieties: [
                    "Adora",
                    "Agata",
                    "Annabelle",
                    "Arinda",
                    "Berber",
                    "Binella",
                    "Climax",
                    "Donald",
                    "Elisabeth",
                    "Fontane",
                    "Gloria",
                    "Inova",
                    "Jaerla",
                    "Junior",
                    "Lady Rosetta",
                    "Lady Olympia",
                    "Leyla",
                    "Linzer Delikatess",
                    "Miriam",
                    "Orinana",
                    "Premiere",
                    "Primura",
                    "Prior",
                    "Rikea",
                    "Romano",
                    "Satellite",
                    "Sirco",
                    "Sirtema",
                    "Tresor",
                    "Ukama",
                ],
                norms: {
                    klei: { standard: 140, nv_area: 112 },
                    zand_nwc: { standard: 140, nv_area: 112 },
                    zand_zuid: { standard: 140, nv_area: 112 },
                    loess: { standard: 140, nv_area: 112 },
                    veen: { standard: 140, nv_area: 112 },
                },
            },
            {
                omschrijving: "lage norm",
                varieties: [
                    "Arcade",
                    "Astarte",
                    "Asterix",
                    "Baraka",
                    "Bartina",
                    "Diamant",
                    "Dolce Vita",
                    "Elles",
                    "Elvira",
                    "Everest",
                    "Florijn",
                    "Kardal",
                    "Karnico",
                    "Maradonna",
                    "Mondial",
                    "Morene",
                    "Mozart",
                    "Picasso",
                    "Remarka",
                    "Resonant",
                    "Rodeo",
                    "Saphire",
                    "Sifra",
                    "Simply Red",
                    "Spirit",
                    "Van Gogh",
                    "Vebesta",
                    "Vento",
                    "Voyager",
                ],
                norms: {
                    klei: { standard: 100, nv_area: 80 },
                    zand_nwc: { standard: 100, nv_area: 80 },
                    zand_zuid: { standard: 100, nv_area: 80 },
                    loess: { standard: 100, nv_area: 80 },
                    veen: { standard: 100, nv_area: 80 },
                },
            },
            {
                omschrijving: "overig",
                norms: {
                    klei: { standard: 120, nv_area: 96 },
                    zand_nwc: { standard: 120, nv_area: 96 },
                    zand_zuid: { standard: 120, nv_area: 96 },
                    loess: { standard: 120, nv_area: 96 },
                    veen: { standard: 120, nv_area: 96 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2:
            "Pootaardappelen, uitgroeiteelt (loofvernietiging na 15 augustus)",
        b_lu_catalogue_match: [
            "nl_1928",
            "nl_1929",
            "nl_2015",
            "nl_2016",
            "nl_3730",
            "nl_3731",
        ],
        type: "aardappel",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewas, zetmeelaardappelen",
        b_lu_catalogue_match: ["nl_2017"],
        type: "aardappel",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 240, nv_area: 192 },
            zand_nwc: { standard: 230, nv_area: 184 },
            zand_zuid: { standard: 184, nv_area: 147 },
            loess: { standard: 184, nv_area: 147 },
            veen: { standard: 230, nv_area: 184 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, suikerbieten",
        b_lu_catalogue_match: ["nl_256"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 145, nv_area: 116 },
            zand_zuid: { standard: 116, nv_area: 93 },
            loess: { standard: 116, nv_area: 93 },
            veen: { standard: 145, nv_area: 116 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Cichorei",
        b_lu_catalogue_match: ["nl_511", "nl_1023", "nl_1024", "nl_1036"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 70, nv_area: 56 },
            zand_nwc: { standard: 70, nv_area: 56 },
            zand_zuid: { standard: 70, nv_area: 56 },
            loess: { standard: 70, nv_area: 56 },
            veen: { standard: 70, nv_area: 56 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, voederbieten",
        b_lu_catalogue_match: ["nl_257"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 165, nv_area: 132 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 132, nv_area: 106 },
            loess: { standard: 132, nv_area: 106 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, wintertarwe",
        b_lu_catalogue_match: ["nl_233", "nl_382"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 245, nv_area: 196 },
            zand_nwc: { standard: 160, nv_area: 128 },
            zand_zuid: { standard: 160, nv_area: 128 },
            loess: { standard: 190, nv_area: 152 },
            veen: { standard: 160, nv_area: 128 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, zomertarwe",
        b_lu_catalogue_match: ["nl_234"],
        type: "akkerbouw",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, wintergerst",
        b_lu_catalogue_match: ["nl_235"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 140, nv_area: 112 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, zomergerst",
        b_lu_catalogue_match: ["nl_236", "nl_381"],
        type: "akkerbouw",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 80, nv_area: 64 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 80, nv_area: 64 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen Triticale",
        b_lu_catalogue_match: ["nl_314"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 160, nv_area: 128 },
            zand_nwc: { standard: 150, nv_area: 120 },
            zand_zuid: { standard: 120, nv_area: 96 },
            loess: { standard: 120, nv_area: 96 },
            veen: { standard: 150, nv_area: 120 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, winterrogge",
        b_lu_catalogue_match: ["nl_237", "nl_6806"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 140, nv_area: 112 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Haver",
        b_lu_catalogue_match: ["nl_238", "nl_670", "nl_6636"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 100, nv_area: 80 },
            zand_nwc: { standard: 100, nv_area: 80 },
            zand_zuid: { standard: 100, nv_area: 80 },
            loess: { standard: 100, nv_area: 80 },
            veen: { standard: 100, nv_area: 80 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, mais",
        b_lu_catalogue_match: [
            "nl_259",
            "nl_316",
            "nl_317",
            "nl_1935",
            "nl_2032",
        ],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 185, nv_area: 148 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 112, nv_area: 90 },
            loess: { standard: 112, nv_area: 90 },
            veen: { standard: 150, nv_area: 120 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Luzerne",
        b_lu_catalogue_match: ["nl_258", "nl_663", "nl_1926", "nl_1949"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        sub_types: [
            {
                omschrijving: "eerste jaar",
                norms: {
                    klei: { standard: 40, nv_area: 32 },
                    zand_nwc: { standard: 40, nv_area: 32 },
                    zand_zuid: { standard: 40, nv_area: 32 },
                    loess: { standard: 40, nv_area: 32 },
                    veen: { standard: 40, nv_area: 32 },
                },
            },
            {
                omschrijving: "volgende jaren",
                norms: {
                    klei: { standard: 0, nv_area: 0 },
                    zand_nwc: { standard: 0, nv_area: 0 },
                    zand_zuid: { standard: 0, nv_area: 0 },
                    loess: { standard: 0, nv_area: 0 },
                    veen: { standard: 0, nv_area: 0 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2:
            "Akkerbouwgewassen, Gras voor industriële verwerking",
        b_lu_catalogue_match: ["nl_3805"],
        type: "gras",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "inzaai in september en eerste jaar",
                norms: {
                    klei: { standard: 30, nv_area: 24 },
                    zand_nwc: { standard: 25, nv_area: 20 },
                    zand_zuid: { standard: 25, nv_area: 20 },
                    loess: { standard: 25, nv_area: 20 },
                    veen: { standard: 25, nv_area: 20 },
                },
            },
            {
                omschrijving: "inzaai voor 15 mei en volgende jaren",
                norms: {
                    klei: { standard: 310, nv_area: 248 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 250, nv_area: 200 },
                    loess: { standard: 250, nv_area: 200 },
                    veen: { standard: 265, nv_area: 212 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Graszaad, Engels raaigras",
        b_lu_catalogue_match: [
            "nl_1919",
            "nl_2030",
            "nl_2031",
            "nl_3506",
            "nl_6750",
            "nl_6751",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        sub_types: [
            {
                omschrijving: "1e jaars",
                norms: {
                    klei: { standard: 165, nv_area: 132 },
                    zand_nwc: { standard: 150, nv_area: 120 },
                    zand_zuid: { standard: 120, nv_area: 96 },
                    loess: { standard: 120, nv_area: 96 },
                    veen: { standard: 155, nv_area: 124 },
                },
            },
            {
                omschrijving: "overjarig",
                norms: {
                    klei: { standard: 200, nv_area: 160 },
                    zand_nwc: { standard: 185, nv_area: 148 },
                    zand_zuid: { standard: 148, nv_area: 118 },
                    loess: { standard: 148, nv_area: 118 },
                    veen: { standard: 190, nv_area: 152 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Rietzwenkgras",
        b_lu_catalogue_match: [
            "nl_1915",
            "nl_3516",
            "nl_3807",
            "nl_6782",
            "nl_6783",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 140, nv_area: 112 },
            zand_nwc: { standard: 130, nv_area: 104 },
            zand_zuid: { standard: 104, nv_area: 83 },
            loess: { standard: 104, nv_area: 83 },
            veen: { standard: 135, nv_area: 108 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Rietzwenkgras, volgteelt",
        b_lu_catalogue_match: [
            "nl_1915",
            "nl_3516",
            "nl_3807",
            "nl_6782",
            "nl_6783",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 60, nv_area: 48 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 40, nv_area: 32 },
            loess: { standard: 40, nv_area: 32 },
            veen: { standard: 55, nv_area: 44 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen,Veldbeemdgras",
        b_lu_catalogue_match: [
            "nl_1916",
            "nl_3523",
            "nl_6746",
            "nl_6788",
            "nl_6789",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 130, nv_area: 104 },
            zand_nwc: { standard: 110, nv_area: 80 },
            zand_zuid: { standard: 100, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 105, nv_area: 84 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen,Veldbeemdgras, volgteelt",
        b_lu_catalogue_match: [
            "nl_1916",
            "nl_3523",
            "nl_6746",
            "nl_6788",
            "nl_6789",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 60, nv_area: 48 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 40, nv_area: 32 },
            loess: { standard: 40, nv_area: 32 },
            veen: { standard: 55, nv_area: 44 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Roodzwenkgras",
        b_lu_catalogue_match: [
            "nl_1917",
            "nl_1918",
            "nl_3808",
            "nl_6784",
            "nl_6785",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        sub_types: [
            {
                omschrijving: "1e jaars",
                norms: {
                    klei: { standard: 85, nv_area: 68 },
                    zand_nwc: { standard: 75, nv_area: 60 },
                    zand_zuid: { standard: 60, nv_area: 48 },
                    loess: { standard: 60, nv_area: 48 },
                    veen: { standard: 80, nv_area: 64 },
                },
            },
            {
                omschrijving: "overjarig",
                norms: {
                    klei: { standard: 115, nv_area: 92 },
                    zand_nwc: { standard: 105, nv_area: 84 },
                    zand_zuid: { standard: 84, nv_area: 67 },
                    loess: { standard: 84, nv_area: 67 },
                    veen: { standard: 110, nv_area: 88 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Roodzwenkgras, volgteelt",
        b_lu_catalogue_match: [
            "nl_1917",
            "nl_1918",
            "nl_3808",
            "nl_6784",
            "nl_6785",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        sub_types: [
            {
                omschrijving: "1e jaars",
                norms: {
                    klei: { standard: 35, nv_area: 28 },
                    zand_nwc: { standard: 35, nv_area: 28 },
                    zand_zuid: { standard: 28, nv_area: 22 },
                    loess: { standard: 28, nv_area: 22 },
                    veen: { standard: 35, nv_area: 28 },
                },
            },
            {
                omschrijving: "overjarig",
                norms: {
                    klei: { standard: 45, nv_area: 36 },
                    zand_nwc: { standard: 45, nv_area: 36 },
                    zand_zuid: { standard: 36, nv_area: 29 },
                    loess: { standard: 36, nv_area: 29 },
                    veen: { standard: 45, nv_area: 36 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Graszaad,Westerwolds",
        b_lu_catalogue_match: ["nl_1919", "nl_3513", "nl_6790", "nl_6791"],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 110, nv_area: 88 },
            zand_nwc: { standard: 100, nv_area: 80 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 105, nv_area: 84 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Graszaad, Italiaans",
        b_lu_catalogue_match: ["nl_1920", "nl_3512", "nl_6754", "nl_6755"],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 130, nv_area: 104 },
            zand_nwc: { standard: 120, nv_area: 96 },
            zand_zuid: { standard: 96, nv_area: 77 },
            loess: { standard: 96, nv_area: 77 },
            veen: { standard: 125, nv_area: 100 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, graszaad overig",
        b_lu_catalogue_match: [
            "nl_383",
            "nl_1914",
            "nl_6768",
            "nl_1034",
            "nl_1035",
            "nl_6752",
        ],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 90, nv_area: 72 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 64, nv_area: 51 },
            loess: { standard: 64, nv_area: 51 },
            veen: { standard: 85, nv_area: 68 },
        },
    },
    {
        cultivation_rvo_table2:
            "Akkerbouwgewassen, graszaad, overig, vanggewas",
        b_lu_catalogue_match: ["nl_6753"],
        type: "graszaad",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 45, nv_area: 36 },
            zand_nwc: { standard: 45, nv_area: 36 },
            zand_zuid: { standard: 36, nv_area: 29 },
            loess: { standard: 36, nv_area: 29 },
            veen: { standard: 45, nv_area: 36 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, graszoden",
        b_lu_catalogue_match: ["nl_1921"],
        type: "gras",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 340, nv_area: 272 },
            zand_nwc: { standard: 340, nv_area: 272 },
            zand_zuid: { standard: 272, nv_area: 218 },
            loess: { standard: 272, nv_area: 218 },
            veen: { standard: 340, nv_area: 272 },
        },
    },
    {
        cultivation_rvo_table2:
            "Akkerbouwgewassen, Ui overig, zaaiui of winterui.",
        b_lu_catalogue_match: ["nl_6660", "nl_6664", "nl_1932", "nl_1933"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 170, nv_area: 136 },
            zand_nwc: { standard: 120, nv_area: 96 },
            zand_zuid: { standard: 120, nv_area: 96 },
            loess: { standard: 120, nv_area: 96 },
            veen: { standard: 120, nv_area: 96 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Ui overig",
        b_lu_catalogue_match: ["nl_263", "nl_1934", "nl_1021"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 120, nv_area: 96 },
            zand_nwc: { standard: 120, nv_area: 96 },
            zand_zuid: { standard: 120, nv_area: 96 },
            loess: { standard: 120, nv_area: 96 },
            veen: { standard: 120, nv_area: 96 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Blauwmaanzaad",
        b_lu_catalogue_match: ["nl_247"],
        type: "akkerbouw",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 110, nv_area: 88 },
            zand_nwc: { standard: 100, nv_area: 80 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 105, nv_area: 84 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Karwij",
        b_lu_catalogue_match: ["nl_246"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 112, nv_area: 90 },
            loess: { standard: 112, nv_area: 90 },
            veen: { standard: 145, nv_area: 116 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, koolzaad",
        b_lu_catalogue_match: ["nl_1922", "nl_1923"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "winter",
                norms: {
                    klei: { standard: 205, nv_area: 164 },
                    zand_nwc: { standard: 190, nv_area: 152 },
                    zand_zuid: { standard: 152, nv_area: 122 },
                    loess: { standard: 152, nv_area: 122 },
                    veen: { standard: 195, nv_area: 156 },
                },
            },
            {
                omschrijving: "zomer",
                norms: {
                    klei: { standard: 120, nv_area: 96 },
                    zand_nwc: { standard: 120, nv_area: 96 },
                    zand_zuid: { standard: 96, nv_area: 77 },
                    loess: { standard: 96, nv_area: 77 },
                    veen: { standard: 120, nv_area: 96 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Vlas",
        b_lu_catalogue_match: ["nl_249", "nl_666", "nl_3736"],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 70, nv_area: 56 },
            zand_nwc: { standard: 70, nv_area: 56 },
            zand_zuid: { standard: 56, nv_area: 45 },
            loess: { standard: 56, nv_area: 45 },
            veen: { standard: 70, nv_area: 56 },
        },
    },
    {
        cultivation_rvo_table2: "Akkerbouwgewassen, Akkerbouwgewassen, overig",
        b_lu_catalogue_match: [
            "nl_1927",
            "nl_2652",
            "nl_375",
            "nl_516",
            "nl_944",
            "nl_3510",
            "nl_6802",
        ],
        type: "akkerbouw",
        is_winterteelt: true,
        is_vanggewas: true,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Spinazie",
        b_lu_catalogue_match: ["nl_2773", "nl_2774"],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "1e teelt",
                norms: {
                    klei: { standard: 260, nv_area: 208 },
                    zand_nwc: { standard: 190, nv_area: 152 },
                    zand_zuid: { standard: 152, nv_area: 122 },
                    loess: { standard: 152, nv_area: 122 },
                    veen: { standard: 200, nv_area: 160 },
                },
            },
            {
                omschrijving: "volgteelt",
                norms: {
                    klei: { standard: 185, nv_area: 148 },
                    zand_nwc: { standard: 145, nv_area: 116 },
                    zand_zuid: { standard: 116, nv_area: 93 },
                    loess: { standard: 116, nv_area: 93 },
                    veen: { standard: 150, nv_area: 120 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Baldgewassen, Spinazie volgteelt",
        b_lu_catalogue_match: ["nl_1022"],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 185, nv_area: 148 },
            zand_nwc: { standard: 145, nv_area: 116 },
            zand_zuid: { standard: 116, nv_area: 93 },
            loess: { standard: 116, nv_area: 93 },
            veen: { standard: 150, nv_area: 120 },
        },
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Slasoorten",
        b_lu_catalogue_match: [
            "nl_2767",
            "nl_2768",
            "nl_2769",
            "nl_2770",
            "nl_2771",
            "nl_2772",
            "nl_2766",
        ],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "1e teelt",
                norms: {
                    klei: { standard: 180, nv_area: 144 },
                    zand_nwc: { standard: 165, nv_area: 132 },
                    zand_zuid: { standard: 132, nv_area: 106 },
                    loess: { standard: 132, nv_area: 106 },
                    veen: { standard: 170, nv_area: 136 },
                },
            },
            {
                omschrijving: "volgteelt",
                norms: {
                    klei: { standard: 105, nv_area: 84 },
                    zand_nwc: { standard: 105, nv_area: 84 },
                    zand_zuid: { standard: 84, nv_area: 67 },
                    loess: { standard: 84, nv_area: 67 },
                    veen: { standard: 105, nv_area: 84 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Andijvie eerste teelt",
        b_lu_catalogue_match: ["nl_2709"],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 170, nv_area: 136 },
            zand_zuid: { standard: 136, nv_area: 109 },
            loess: { standard: 136, nv_area: 109 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Andijvie eerste teelt volgteelt",
        b_lu_catalogue_match: ["nl_2708"],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "1e teelt",
                norms: {
                    klei: { standard: 180, nv_area: 144 },
                    zand_nwc: { standard: 170, nv_area: 136 },
                    zand_zuid: { standard: 136, nv_area: 109 },
                    loess: { standard: 136, nv_area: 109 },
                    veen: { standard: 170, nv_area: 136 },
                },
            },
            {
                omschrijving: "volgteelt",
                norms: {
                    klei: { standard: 90, nv_area: 72 },
                    zand_nwc: { standard: 90, nv_area: 72 },
                    zand_zuid: { standard: 72, nv_area: 58 },
                    loess: { standard: 72, nv_area: 58 },
                    veen: { standard: 90, nv_area: 72 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Selderij, bleek/groen",
        b_lu_catalogue_match: ["nl_2765"],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Prei",
        b_lu_catalogue_match: [
            "nl_2749",
            "nl_2750",
            "nl_2799",
            "nl_2800",
            "nl_2801",
            "nl_2802",
        ],
        type: "bladgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 245, nv_area: 196 },
            zand_nwc: { standard: 225, nv_area: 180 },
            zand_zuid: { standard: 180, nv_area: 144 },
            loess: { standard: 180, nv_area: 144 },
            veen: { standard: 235, nv_area: 188 },
        },
    },
    {
        cultivation_rvo_table2: "Bladgewassen, Bladgewassen overig",
        b_lu_catalogue_match: ["nl_2791", "nl_2792"],
        type: "bladgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "eenmalige oogst",
                norms: {
                    klei: { standard: 150, nv_area: 120 },
                    zand_nwc: { standard: 140, nv_area: 112 },
                    zand_zuid: { standard: 112, nv_area: 90 },
                    loess: { standard: 112, nv_area: 90 },
                    veen: { standard: 145, nv_area: 116 },
                },
            },
            {
                omschrijving: "meermalige oogst",
                norms: {
                    klei: { standard: 275, nv_area: 220 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 200, nv_area: 160 },
                    loess: { standard: 200, nv_area: 160 },
                    veen: { standard: 260, nv_area: 208 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Spruitkool",
        b_lu_catalogue_match: ["nl_2777", "nl_2778"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 290, nv_area: 232 },
            zand_nwc: { standard: 265, nv_area: 212 },
            zand_zuid: { standard: 212, nv_area: 170 },
            loess: { standard: 212, nv_area: 170 },
            veen: { standard: 275, nv_area: 220 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Witte Kool",
        b_lu_catalogue_match: ["nl_2789", "nl_2790"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 320, nv_area: 256 },
            zand_nwc: { standard: 290, nv_area: 232 },
            zand_zuid: { standard: 232, nv_area: 186 },
            loess: { standard: 232, nv_area: 186 },
            veen: { standard: 305, nv_area: 244 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Rode kool",
        b_lu_catalogue_match: ["nl_2759", "nl_2760"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 285, nv_area: 228 },
            zand_nwc: { standard: 260, nv_area: 208 },
            zand_zuid: { standard: 208, nv_area: 166 },
            loess: { standard: 208, nv_area: 166 },
            veen: { standard: 270, nv_area: 216 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Savooiekool",
        b_lu_catalogue_match: ["nl_2761", "nl_2762"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 285, nv_area: 228 },
            zand_nwc: { standard: 260, nv_area: 208 },
            zand_zuid: { standard: 208, nv_area: 166 },
            loess: { standard: 208, nv_area: 166 },
            veen: { standard: 270, nv_area: 216 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Spitskool",
        b_lu_catalogue_match: ["nl_2775", "nl_2776"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 285, nv_area: 228 },
            zand_nwc: { standard: 260, nv_area: 208 },
            zand_zuid: { standard: 208, nv_area: 166 },
            loess: { standard: 208, nv_area: 166 },
            veen: { standard: 270, nv_area: 216 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Bloemkool",
        b_lu_catalogue_match: [
            "nl_2713",
            "nl_2714",
            "nl_2795",
            "nl_2796",
            "nl_2797",
            "nl_2798",
        ],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 230, nv_area: 184 },
            zand_nwc: { standard: 210, nv_area: 168 },
            zand_zuid: { standard: 168, nv_area: 134 },
            loess: { standard: 168, nv_area: 134 },
            veen: { standard: 220, nv_area: 176 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Broccoli",
        b_lu_catalogue_match: ["nl_2719", "nl_2720"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 270, nv_area: 216 },
            zand_nwc: { standard: 235, nv_area: 188 },
            zand_zuid: { standard: 188, nv_area: 150 },
            loess: { standard: 188, nv_area: 150 },
            veen: { standard: 245, nv_area: 196 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Chinese kool",
        b_lu_catalogue_match: ["nl_2721", "nl_2722"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 155, nv_area: 124 },
            zand_zuid: { standard: 124, nv_area: 99 },
            loess: { standard: 124, nv_area: 99 },
            veen: { standard: 160, nv_area: 128 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, boerenkool",
        b_lu_catalogue_match: ["nl_2715", "nl_2716"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 170, nv_area: 136 },
            zand_nwc: { standard: 155, nv_area: 124 },
            zand_zuid: { standard: 124, nv_area: 99 },
            loess: { standard: 124, nv_area: 99 },
            veen: { standard: 160, nv_area: 128 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Paksoi",
        b_lu_catalogue_match: ["nl_2745", "nl_2746"],
        type: "koolgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 132, nv_area: 106 },
            loess: { standard: 132, nv_area: 106 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2: "Koolgewassen, Raapstelen",
        b_lu_catalogue_match: ["nl_2753", "nl_2754", "nl_664"],
        type: "koolgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 140, nv_area: 112 },
            zand_nwc: { standard: 130, nv_area: 104 },
            zand_zuid: { standard: 104, nv_area: 83 },
            loess: { standard: 104, nv_area: 83 },
            veen: { standard: 135, nv_area: 108 },
        },
    },
    {
        cultivation_rvo_table2: "Kruiden",
        b_lu_catalogue_match: ["nl_2743", "nl_2744"],
        type: "kruiden",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "bladgewas, eenmalige oogst",
                norms: {
                    klei: { standard: 150, nv_area: 120 },
                    zand_nwc: { standard: 140, nv_area: 112 },
                    zand_zuid: { standard: 112, nv_area: 90 },
                    loess: { standard: 112, nv_area: 90 },
                    veen: { standard: 145, nv_area: 116 },
                },
            },
            {
                omschrijving: "bladgewas, meermalig oogsten",
                norms: {
                    klei: { standard: 275, nv_area: 220 },
                    zand_nwc: { standard: 250, nv_area: 200 },
                    zand_zuid: { standard: 200, nv_area: 160 },
                    loess: { standard: 200, nv_area: 160 },
                    veen: { standard: 260, nv_area: 208 },
                },
            },
            {
                omschrijving: "wortelgewassen",
                norms: {
                    klei: { standard: 200, nv_area: 160 },
                    zand_nwc: { standard: 185, nv_area: 148 },
                    zand_zuid: { standard: 148, nv_area: 118 },
                    loess: { standard: 148, nv_area: 118 },
                    veen: { standard: 190, nv_area: 152 },
                },
            },
            {
                omschrijving: "zaadgewassen",
                norms: {
                    klei: { standard: 100, nv_area: 80 },
                    zand_nwc: { standard: 90, nv_area: 72 },
                    zand_zuid: { standard: 72, nv_area: 58 },
                    loess: { standard: 72, nv_area: 58 },
                    veen: { standard: 95, nv_area: 76 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Kruiden, bladgewas, eemalige oogst",
        b_lu_catalogue_match: [
            "nl_1019",
            "nl_1020",
            "nl_1028",
            "nl_1029",
            "nl_1030",
            "nl_1031",
            "nl_1032",
            "nl_1037",
            "nl_1038",
            "nl_654",
            "nl_6749",
        ],
        type: "kruiden",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 112, nv_area: 90 },
            loess: { standard: 112, nv_area: 90 },
            veen: { standard: 145, nv_area: 116 },
        },
    },
    {
        cultivation_rvo_table2: "Kruiden, wortelgewassen",
        b_lu_catalogue_match: ["nl_652"],
        type: "kruiden",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Kruiden, zaadgewassen",
        b_lu_catalogue_match: ["nl_655"],
        type: "kruiden",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 100, nv_area: 80 },
            zand_nwc: { standard: 90, nv_area: 72 },
            zand_zuid: { standard: 72, nv_area: 58 },
            loess: { standard: 72, nv_area: 58 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2:
            "Vruchtgewassen, Aardbei (wachtbed, vermeerdering)",
        b_lu_catalogue_match: ["nl_2700", "nl_2701"],
        type: "vruchtgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 120, nv_area: 96 },
            zand_nwc: { standard: 110, nv_area: 88 },
            zand_zuid: { standard: 88, nv_area: 70 },
            loess: { standard: 88, nv_area: 70 },
            veen: { standard: 115, nv_area: 92 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, Aardbei (productie)",
        b_lu_catalogue_match: ["nl_2702"],
        type: "vruchtgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 170, nv_area: 136 },
            zand_nwc: { standard: 155, nv_area: 124 },
            zand_zuid: { standard: 124, nv_area: 99 },
            loess: { standard: 124, nv_area: 99 },
            veen: { standard: 160, nv_area: 128 },
        },
    },
    {
        cultivation_rvo_table2:
            "Vruchtgewassen, Komkommerachtigen (augurk, courgette, meloen, pompoen)",
        b_lu_catalogue_match: [
            "nl_2723",
            "nl_2724",
            "nl_2729",
            "nl_2730",
            "nl_2731",
            "nl_2732",
            "nl_2733",
            "nl_2734",
            "nl_2735",
            "nl_2736",
        ],
        type: "vruchtgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 190, nv_area: 152 },
            zand_nwc: { standard: 175, nv_area: 140 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 180, nv_area: 144 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, suikermais",
        b_lu_catalogue_match: ["nl_814"],
        type: "vruchtgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, stam/stokboon",
        b_lu_catalogue_match: ["nl_2779", "nl_2780", "nl_2781", "nl_2782"],
        type: "vruchtgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 120, nv_area: 96 },
            zand_nwc: { standard: 110, nv_area: 88 },
            zand_zuid: { standard: 88, nv_area: 70 },
            loess: { standard: 88, nv_area: 70 },
            veen: { standard: 115, nv_area: 92 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, Landbouwstambonen, rijp zaad",
        b_lu_catalogue_match: ["nl_2751", "nl_2752"],
        type: "vruchtgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 135, nv_area: 108 },
            zand_nwc: { standard: 135, nv_area: 108 },
            zand_zuid: { standard: 108, nv_area: 86 },
            loess: { standard: 108, nv_area: 86 },
            veen: { standard: 135, nv_area: 108 },
        },
    },
    {
        cultivation_rvo_table2:
            "Vruchtgewassen, Veld- en tuinbonen, vers + rijp zaad",
        b_lu_catalogue_match: [
            "nl_311",
            "nl_665",
            "nl_853",
            "nl_854",
            "nl_6767",
        ],
        type: "vruchtgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 50, nv_area: 40 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 40, nv_area: 32 },
            loess: { standard: 40, nv_area: 32 },
            veen: { standard: 50, nv_area: 40 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, Tuinbonen, vers/peulen",
        b_lu_catalogue_match: ["nl_242"],
        type: "vruchtgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 75, nv_area: 60 },
            zand_nwc: { standard: 75, nv_area: 60 },
            zand_zuid: { standard: 75, nv_area: 60 },
            loess: { standard: 75, nv_area: 60 },
            veen: { standard: 75, nv_area: 60 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, Erwt, vers + rijp zaad",
        b_lu_catalogue_match: ["nl_241", "nl_244", "nl_308"],
        type: "vruchtgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 30, nv_area: 24 },
            zand_nwc: { standard: 30, nv_area: 24 },
            zand_zuid: { standard: 30, nv_area: 24 },
            loess: { standard: 30, nv_area: 24 },
            veen: { standard: 30, nv_area: 24 },
        },
    },
    {
        cultivation_rvo_table2: "Vruchtgewassen, Peul",
        b_lu_catalogue_match: ["nl_2747", "nl_2748"],
        type: "vruchtgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 90, nv_area: 72 },
            zand_nwc: { standard: 85, nv_area: 68 },
            zand_zuid: { standard: 68, nv_area: 54 },
            loess: { standard: 68, nv_area: 54 },
            veen: { standard: 85, nv_area: 68 },
        },
    },
    {
        cultivation_rvo_table2:
            "Stengel/knol/wortelgewassen, Asperges (excl. Opkweek)",
        b_lu_catalogue_match: ["nl_2710"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 85, nv_area: 68 },
            zand_nwc: { standard: 75, nv_area: 60 },
            zand_zuid: { standard: 60, nv_area: 48 },
            loess: { standard: 60, nv_area: 48 },
            veen: { standard: 80, nv_area: 64 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Knolselderij",
        b_lu_catalogue_match: ["nl_2725", "nl_2726"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2:
            "Stengel/knol/wortelgewassen, Knolvenkel/venkel",
        b_lu_catalogue_match: ["nl_2727", "nl_2728"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 132, nv_area: 106 },
            loess: { standard: 132, nv_area: 106 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Koolraap",
        b_lu_catalogue_match: ["nl_2737", "nl_2738"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 170, nv_area: 136 },
            zand_nwc: { standard: 155, nv_area: 124 },
            zand_zuid: { standard: 124, nv_area: 99 },
            loess: { standard: 124, nv_area: 99 },
            veen: { standard: 160, nv_area: 128 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Koolrabi",
        b_lu_catalogue_match: ["nl_2739", "nl_2740"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 180, nv_area: 144 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 132, nv_area: 106 },
            loess: { standard: 132, nv_area: 106 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2:
            "Stengel/knol/wortelgewassen, Kroten/rode bieten",
        b_lu_catalogue_match: ["nl_2741", "nl_2742"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 185, nv_area: 148 },
            zand_nwc: { standard: 170, nv_area: 136 },
            zand_zuid: { standard: 136, nv_area: 109 },
            loess: { standard: 136, nv_area: 109 },
            veen: { standard: 175, nv_area: 140 },
        },
    },
    {
        cultivation_rvo_table2:
            "Stengel/knol/wortelgewassen, winterpeen/waspeen",
        b_lu_catalogue_match: ["nl_2783", "nl_2784", "nl_2785", "nl_2786"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 110, nv_area: 88 },
            zand_nwc: { standard: 110, nv_area: 88 },
            zand_zuid: { standard: 110, nv_area: 88 },
            loess: { standard: 110, nv_area: 88 },
            veen: { standard: 110, nv_area: 88 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, bospeen",
        b_lu_catalogue_match: ["nl_2717", "nl_2718"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 50, nv_area: 40 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 50, nv_area: 40 },
            loess: { standard: 50, nv_area: 40 },
            veen: { standard: 50, nv_area: 40 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Rabarber",
        b_lu_catalogue_match: ["nl_2755", "nl_2756"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 250, nv_area: 200 },
            zand_nwc: { standard: 230, nv_area: 184 },
            zand_zuid: { standard: 184, nv_area: 147 },
            loess: { standard: 184, nv_area: 147 },
            veen: { standard: 240, nv_area: 192 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Radijs",
        b_lu_catalogue_match: ["nl_2757", "nl_2758"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 80, nv_area: 64 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 64, nv_area: 51 },
            loess: { standard: 64, nv_area: 51 },
            veen: { standard: 80, nv_area: 64 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Schorseneren",
        b_lu_catalogue_match: ["nl_2763", "nl_2764"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 170, nv_area: 136 },
            zand_nwc: { standard: 170, nv_area: 136 },
            zand_zuid: { standard: 170, nv_area: 136 },
            loess: { standard: 170, nv_area: 136 },
            veen: { standard: 170, nv_area: 136 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, Witlof",
        b_lu_catalogue_match: ["nl_2787", "nl_2788"],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 100, nv_area: 80 },
            zand_nwc: { standard: 100, nv_area: 80 },
            zand_zuid: { standard: 100, nv_area: 80 },
            loess: { standard: 100, nv_area: 80 },
            veen: { standard: 100, nv_area: 80 },
        },
    },
    {
        cultivation_rvo_table2: "Stengel/knol/wortelgewassen, overig",
        b_lu_catalogue_match: [
            "nl_2793",
            "nl_2794",
            "nl_1949",
            "nl_2711",
            "nl_2712",
            "nl_3521",
            "nl_6632",
        ],
        type: "stengel_knol_wortelgewas",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 185, nv_area: 148 },
            zand_zuid: { standard: 148, nv_area: 118 },
            loess: { standard: 148, nv_area: 118 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Groenbemesters, niet-vlinderbloemige",
        b_lu_catalogue_match: [
            "nl_427",
            "nl_428",
            "nl_3502",
            "nl_3503",
            "nl_3504",
            "nl_3505",
            "nl_3507",
            "nl_3508",
            "nl_3514",
            "nl_3517",
            "nl_3519",
            "nl_3520",
        ],
        type: "groenbemester",
        is_vanggewas: true,
        is_winterteelt: false,
        norms: {
            klei: { standard: 60, nv_area: 48 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 50, nv_area: 40 },
            loess: { standard: 50, nv_area: 40 },
            veen: { standard: 60, nv_area: 48 },
        },
    },
    {
        cultivation_rvo_table2: "Groenbemesters, vlinderbloemige",
        b_lu_catalogue_match: [
            "nl_426",
            "nl_6763",
            "nl_6762",
            "nl_800",
            "nl_801",
            "nl_802",
            "nl_803",
            "nl_6757",
            "nl_6756",
            "nl_6759",
            "nl_6758",
            "nl_6761",
            "nl_6760",
            "nl_3518",
            "nl_6765",
            "nl_6764",
            "nl_6769",
        ],
        type: "groenbemester",
        is_vanggewas: true,
        is_winterteelt: false,
        norms: {
            klei: { standard: 0, nv_area: 0 },
            zand_nwc: { standard: 0, nv_area: 0 },
            zand_zuid: { standard: 0, nv_area: 0 },
            loess: { standard: 0, nv_area: 0 },
            veen: { standard: 0, nv_area: 0 },
        },
    },
    {
        cultivation_rvo_table2:
            "Graszaadstoppel ter vernietiging in najaar of vroege voorjaar",
        b_lu_catalogue_match: [],
        type: "groenbemester",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 60, nv_area: 48 },
            zand_nwc: { standard: 50, nv_area: 40 },
            zand_zuid: { standard: 50, nv_area: 40 },
            loess: { standard: 50, nv_area: 40 },
            veen: { standard: 60, nv_area: 48 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Acidanthera",
        b_lu_catalogue_match: [],
        type: "bloembol",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 255, nv_area: 204 },
            zand_nwc: { standard: 240, nv_area: 192 },
            zand_zuid: { standard: 240, nv_area: 192 },
            loess: { standard: 240, nv_area: 192 },
            veen: { standard: 240, nv_area: 192 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Anemone coronaria",
        b_lu_catalogue_match: [],
        type: "bloembol",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 130, nv_area: 104 },
            zand_nwc: { standard: 125, nv_area: 100 },
            zand_zuid: { standard: 125, nv_area: 100 },
            loess: { standard: 125, nv_area: 100 },
            veen: { standard: 125, nv_area: 100 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Fritillaria imperialis",
        b_lu_catalogue_match: [],
        type: "bloembol",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 135, nv_area: 108 },
            zand_nwc: { standard: 130, nv_area: 104 },
            zand_zuid: { standard: 130, nv_area: 104 },
            loess: { standard: 130, nv_area: 104 },
            veen: { standard: 130, nv_area: 104 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Hyacint",
        b_lu_catalogue_match: [
            "nl_970",
            "nl_971",
            "nl_999",
            "nl_1016",
            "nl_1017",
            "nl_1018",
        ],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 220, nv_area: 176 },
            zand_nwc: { standard: 210, nv_area: 168 },
            zand_zuid: { standard: 210, nv_area: 168 },
            loess: { standard: 210, nv_area: 168 },
            veen: { standard: 210, nv_area: 168 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Iris",
        b_lu_catalogue_match: [
            "nl_973",
            "nl_974",
            "nl_1000",
            "nl_1051",
            "nl_1052",
        ],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "grofbollig",
                norms: {
                    klei: { standard: 170, nv_area: 136 },
                    zand_nwc: { standard: 160, nv_area: 128 },
                    zand_zuid: { standard: 160, nv_area: 128 },
                    loess: { standard: 160, nv_area: 128 },
                    veen: { standard: 160, nv_area: 128 },
                },
            },
            {
                omschrijving: "fijnbollig",
                norms: {
                    klei: { standard: 140, nv_area: 112 },
                    zand_nwc: { standard: 135, nv_area: 108 },
                    zand_zuid: { standard: 135, nv_area: 108 },
                    loess: { standard: 135, nv_area: 108 },
                    veen: { standard: 135, nv_area: 108 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Krokus",
        b_lu_catalogue_match: ["nl_976", "nl_977", "nl_1001"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "grote gele",
                norms: {
                    klei: { standard: 175, nv_area: 140 },
                    zand_nwc: { standard: 165, nv_area: 132 },
                    zand_zuid: { standard: 165, nv_area: 132 },
                    loess: { standard: 165, nv_area: 132 },
                    veen: { standard: 165, nv_area: 132 },
                },
            },
            {
                omschrijving: "overig",
                norms: {
                    klei: { standard: 90, nv_area: 72 },
                    zand_nwc: { standard: 85, nv_area: 68 },
                    zand_zuid: { standard: 85, nv_area: 68 },
                    loess: { standard: 85, nv_area: 68 },
                    veen: { standard: 85, nv_area: 68 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Narcis",
        b_lu_catalogue_match: ["nl_982", "nl_983", "nl_1003"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 145, nv_area: 116 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Tulp",
        b_lu_catalogue_match: ["nl_985", "nl_986", "nl_1004"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 190, nv_area: 152 },
            zand_zuid: { standard: 190, nv_area: 152 },
            loess: { standard: 190, nv_area: 152 },
            veen: { standard: 190, nv_area: 152 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Dahlia",
        b_lu_catalogue_match: ["nl_964", "nl_965", "nl_997"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 110, nv_area: 88 },
            zand_nwc: { standard: 105, nv_area: 84 },
            zand_zuid: { standard: 105, nv_area: 84 },
            loess: { standard: 105, nv_area: 84 },
            veen: { standard: 105, nv_area: 84 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Gladiool",
        b_lu_catalogue_match: ["nl_967", "nl_968", "nl_998"],
        type: "bloembol",
        is_winterteelt: false,
        is_vanggewas: false,
        sub_types: [
            {
                omschrijving: "pitten",
                norms: {
                    klei: { standard: 260, nv_area: 208 },
                    zand_nwc: { standard: 245, nv_area: 196 },
                    zand_zuid: { standard: 245, nv_area: 196 },
                    loess: { standard: 245, nv_area: 196 },
                    veen: { standard: 245, nv_area: 196 },
                },
            },
            {
                omschrijving: "kralen",
                norms: {
                    klei: { standard: 190, nv_area: 152 },
                    zand_nwc: { standard: 180, nv_area: 144 },
                    zand_zuid: { standard: 180, nv_area: 144 },
                    loess: { standard: 180, nv_area: 144 },
                    veen: { standard: 180, nv_area: 144 },
                },
            },
        ],
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Knolbegonia",
        b_lu_catalogue_match: [],
        type: "bloembol",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 145, nv_area: 116 },
            zand_zuid: { standard: 145, nv_area: 116 },
            loess: { standard: 145, nv_area: 116 },
            veen: { standard: 145, nv_area: 116 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen,Lelie",
        b_lu_catalogue_match: ["nl_979", "nl_980", "nl_1002"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 155, nv_area: 124 },
            zand_nwc: { standard: 145, nv_area: 116 },
            zand_zuid: { standard: 145, nv_area: 116 },
            loess: { standard: 145, nv_area: 116 },
            veen: { standard: 145, nv_area: 116 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, Zantedeschia",
        b_lu_catalogue_match: ["nl_988", "nl_989", "nl_1005"],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 120, nv_area: 96 },
            zand_nwc: { standard: 120, nv_area: 96 },
            zand_zuid: { standard: 120, nv_area: 96 },
            loess: { standard: 120, nv_area: 96 },
            veen: { standard: 120, nv_area: 96 },
        },
    },
    {
        cultivation_rvo_table2: "Bloembollengewassen, overig",
        b_lu_catalogue_match: [
            "nl_176",
            "nl_994",
            "nl_995",
            "nl_1006",
            "nl_1007",
            "nl_1010",
            "nl_1011",
            "nl_1012",
            "nl_1013",
            "nl_1014",
            "nl_1015",
            "nl_1025",
            "nl_1026",
            "nl_1027",
            "nl_6795",
            "nl_6796",
            "nl_6797",
            "nl_6803",
            "nl_6804",
            "nl_6805",
        ],
        type: "bloembol",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 165, nv_area: 132 },
            zand_nwc: { standard: 155, nv_area: 124 },
            zand_zuid: { standard: 155, nv_area: 124 },
            loess: { standard: 155, nv_area: 124 },
            veen: { standard: 155, nv_area: 124 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, Appel",
        b_lu_catalogue_match: ["nl_1095", "nl_1096"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, blauwe bes",
        b_lu_catalogue_match: ["nl_1869", "nl_1874", "nl_1047"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 100, nv_area: 80 },
            zand_nwc: { standard: 95, nv_area: 76 },
            zand_zuid: { standard: 95, nv_area: 76 },
            loess: { standard: 95, nv_area: 76 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, braam",
        b_lu_catalogue_match: ["nl_2327"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, framboos",
        b_lu_catalogue_match: ["nl_2326"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, kers",
        b_lu_catalogue_match: ["nl_1872", "nl_2328", "nl_1100", "nl_2645"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, Peer",
        b_lu_catalogue_match: ["nl_1097", "nl_1098"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, Pruimen",
        b_lu_catalogue_match: ["nl_1870"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, rode bes",
        b_lu_catalogue_match: ["nl_2325"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 140, nv_area: 112 },
            zand_zuid: { standard: 140, nv_area: 112 },
            loess: { standard: 140, nv_area: 112 },
            veen: { standard: 140, nv_area: 112 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, wijnbouw",
        b_lu_catalogue_match: ["nl_1099"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 100, nv_area: 80 },
            zand_nwc: { standard: 95, nv_area: 76 },
            zand_zuid: { standard: 95, nv_area: 76 },
            loess: { standard: 95, nv_area: 76 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2: "Fruitteeltgewassen, zwarte bes",
        b_lu_catalogue_match: ["nl_1873"],
        type: "fruitteelt",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 165, nv_area: 132 },
            zand_zuid: { standard: 165, nv_area: 132 },
            loess: { standard: 165, nv_area: 132 },
            veen: { standard: 165, nv_area: 132 },
        },
    },
    {
        cultivation_rvo_table2: "Buitenbloemen, hoog",
        b_lu_catalogue_match: ["nl_1025", "nl_1026", "nl_1054"],
        type: "buitenbloem",
        is_winterteelt: true,
        is_vanggewas: false,
        varieties: [
            "Alchemilla mollis",
            "Carthamus",
            "Gypsophila paniculata",
            "Lymonium",
            "Lysimachia",
            "Paeonia",
            "Solidago",
            "Veronica",
        ],
        norms: {
            klei: { standard: 200, nv_area: 160 },
            zand_nwc: { standard: 200, nv_area: 160 },
            zand_zuid: { standard: 200, nv_area: 160 },
            loess: { standard: 200, nv_area: 160 },
            veen: { standard: 200, nv_area: 160 },
        },
    },
    {
        cultivation_rvo_table2: "Buitenbloemen, overig",
        b_lu_catalogue_match: [
            "nl_174",
            "nl_515",
            "nl_636",
            "nl_637",
            "nl_653",
            "nl_656",
            "nl_657",
            "nl_991",
            "nl_992",
            "nl_1039",
            "nl_1040",
            "nl_1042",
            "nl_1043",
            "nl_1044",
            "nl_1045",
            "nl_1046",
            "nl_1048",
            "nl_1049",
            "nl_1050",
            "nl_1055",
        ],
        type: "buitenbloem",
        is_winterteelt: true,
        is_vanggewas: true,
        varieties: [],
        norms: {
            klei: { standard: 150, nv_area: 120 },
            zand_nwc: { standard: 150, nv_area: 120 },
            zand_zuid: { standard: 150, nv_area: 120 },
            loess: { standard: 150, nv_area: 120 },
            veen: { standard: 150, nv_area: 120 },
        },
    },
    {
        cultivation_rvo_table2: "Buitenbloemen, Tagetes",
        b_lu_catalogue_match: ["nl_346", "nl_347", "nl_669", "nl_671"],
        type: "buitenbloem",
        is_vanggewas: true,
        is_winterteelt: false,
        norms: {
            klei: { standard: 90, nv_area: 72 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 90, nv_area: 72 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Laanbomen onderstammen",
        b_lu_catalogue_match: ["nl_1070"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 40, nv_area: 32 },
            zand_nwc: { standard: 40, nv_area: 32 },
            zand_zuid: { standard: 40, nv_area: 32 },
            loess: { standard: 40, nv_area: 32 },
            veen: { standard: 40, nv_area: 32 },
        },
    },
    {
        cultivation_rvo_table2:
            "Boomkwekerijgewassen, Laanbomen/parkbomen, opzetters",
        b_lu_catalogue_match: ["nl_1071", "nl_1072"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 115, nv_area: 92 },
            zand_nwc: { standard: 115, nv_area: 92 },
            zand_zuid: { standard: 115, nv_area: 92 },
            loess: { standard: 115, nv_area: 92 },
            veen: { standard: 115, nv_area: 92 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen,Sierheesters",
        b_lu_catalogue_match: ["nl_1075"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 75, nv_area: 60 },
            zand_nwc: { standard: 75, nv_area: 60 },
            zand_zuid: { standard: 75, nv_area: 60 },
            loess: { standard: 75, nv_area: 60 },
            veen: { standard: 75, nv_area: 60 },
        },
    },
    {
        cultivation_rvo_table2:
            "Boomkwekerijgewassen, coniferen incl kerstsparren en dennen",
        b_lu_catalogue_match: ["nl_796", "nl_1074"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 80, nv_area: 64 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 80, nv_area: 64 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Rozen",
        b_lu_catalogue_match: ["nl_1073"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 70, nv_area: 56 },
            zand_nwc: { standard: 70, nv_area: 56 },
            zand_zuid: { standard: 70, nv_area: 56 },
            loess: { standard: 70, nv_area: 56 },
            veen: { standard: 70, nv_area: 56 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Bos- en haagplantsoen",
        b_lu_catalogue_match: ["nl_1067", "nl_863"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 95, nv_area: 76 },
            zand_nwc: { standard: 95, nv_area: 76 },
            zand_zuid: { standard: 95, nv_area: 76 },
            loess: { standard: 95, nv_area: 76 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Vaste planten",
        b_lu_catalogue_match: ["nl_1080"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 175, nv_area: 140 },
            zand_nwc: { standard: 175, nv_area: 140 },
            zand_zuid: { standard: 175, nv_area: 140 },
            loess: { standard: 175, nv_area: 140 },
            veen: { standard: 175, nv_area: 140 },
        },
    },
    {
        cultivation_rvo_table2:
            "Boomkwekerijgewassen, Vruchtbomen, onderstammen",
        b_lu_catalogue_match: ["nl_1078"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 30, nv_area: 24 },
            zand_nwc: { standard: 30, nv_area: 24 },
            zand_zuid: { standard: 30, nv_area: 24 },
            loess: { standard: 30, nv_area: 24 },
            veen: { standard: 30, nv_area: 24 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, moerbomen",
        b_lu_catalogue_match: ["nl_1077"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 110, nv_area: 88 },
            zand_nwc: { standard: 110, nv_area: 88 },
            zand_zuid: { standard: 110, nv_area: 88 },
            loess: { standard: 110, nv_area: 88 },
            veen: { standard: 110, nv_area: 88 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Vruchtbomen, overig,",
        b_lu_catalogue_match: ["nl_1079"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 135, nv_area: 108 },
            zand_nwc: { standard: 105, nv_area: 84 },
            zand_zuid: { standard: 105, nv_area: 84 },
            loess: { standard: 105, nv_area: 84 },
            veen: { standard: 105, nv_area: 84 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Trek- en besheesters",
        b_lu_catalogue_match: ["nl_1076"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 80, nv_area: 64 },
            zand_nwc: { standard: 80, nv_area: 64 },
            zand_zuid: { standard: 80, nv_area: 64 },
            loess: { standard: 80, nv_area: 64 },
            veen: { standard: 80, nv_area: 64 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Snijgroen",
        b_lu_catalogue_match: ["nl_1876"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 95, nv_area: 76 },
            zand_nwc: { standard: 95, nv_area: 76 },
            zand_zuid: { standard: 95, nv_area: 76 },
            loess: { standard: 95, nv_area: 76 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Ericaceae",
        b_lu_catalogue_match: ["nl_1069"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 70, nv_area: 56 },
            zand_nwc: { standard: 70, nv_area: 56 },
            zand_zuid: { standard: 70, nv_area: 56 },
            loess: { standard: 70, nv_area: 56 },
            veen: { standard: 70, nv_area: 56 },
        },
    },
    {
        cultivation_rvo_table2: "Boomkwekerijgewassen, Buxus",
        b_lu_catalogue_match: ["nl_1068"],
        type: "boomkwekerij",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 95, nv_area: 76 },
            zand_nwc: { standard: 95, nv_area: 76 },
            zand_zuid: { standard: 95, nv_area: 76 },
            loess: { standard: 95, nv_area: 76 },
            veen: { standard: 95, nv_area: 76 },
        },
    },
    {
        cultivation_rvo_table2:
            "Boomkwekerijgewassen, Snelgroeiende houtsoorten voor biomassaproductie",
        b_lu_catalogue_match: ["nl_864"],
        type: "bosbouw",
        is_winterteelt: true,
        is_vanggewas: false,
        norms: {
            klei: { standard: 90, nv_area: 72 },
            zand_nwc: { standard: 90, nv_area: 72 },
            zand_zuid: { standard: 90, nv_area: 72 },
            loess: { standard: 90, nv_area: 72 },
            veen: { standard: 90, nv_area: 72 },
        },
    },
    {
        cultivation_rvo_table2:
            "Akkerbouwgewas, Aardappel, bestrijdingsmaatregel",
        b_lu_catalogue_match: ["nl_2026"],
        type: "aardappel",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 0, nv_area: 0 },
            zand_nwc: { standard: 0, nv_area: 0 },
            zand_zuid: { standard: 0, nv_area: 0 },
            loess: { standard: 0, nv_area: 0 },
            veen: { standard: 0, nv_area: 0 },
        },
    },
    {
        cultivation_rvo_table2: "Geen plaatsingsruimte",
        b_lu_catalogue_match: [
            "nl_338",
            "nl_1940",
            "nl_2300",
            "nl_3801",
            "nl_3802",
            "nl_6798",
            "nl_6794",
            "nl_6809",
            "nl_6800",
            "nl_6807",
        ],
        type: "Geen gewas",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 0, nv_area: 0 },
            zand_nwc: { standard: 0, nv_area: 0 },
            zand_zuid: { standard: 0, nv_area: 0 },
            loess: { standard: 0, nv_area: 0 },
            veen: { standard: 0, nv_area: 0 },
        },
    },
    {
        cultivation_rvo_table2: "Geen plaatsingsruimte",
        b_lu_catalogue_match: [
            "nl_343",
            "nl_794",
            "nl_795",
            "nl_2617",
            "nl_2618",
            "nl_2619",
            "nl_2620",
            "nl_2621",
            "nl_2622",
            "nl_2624",
            "nl_2625",
            "nl_2626",
            "nl_2628",
            "nl_2629",
            "nl_2630",
            "nl_2631",
            "nl_2633",
            "nl_2634",
            "nl_2636",
            "nl_2637",
            "nl_2638",
            "nl_2639",
            "nl_2642",
            "nl_6808",
            "nl_6801",
            "nl_6793",
        ],
        type: "Landschapselement",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 0, nv_area: 0 },
            zand_nwc: { standard: 0, nv_area: 0 },
            zand_zuid: { standard: 0, nv_area: 0 },
            loess: { standard: 0, nv_area: 0 },
            veen: { standard: 0, nv_area: 0 },
        },
    },
    {
        cultivation_rvo_table2: "Geen plaatsingsruimte",
        b_lu_catalogue_match: [
            "nl_6520",
            "nl_6521",
            "nl_6522",
            "nl_6792",
            "nl_6766",
            "nl_6799",
        ],
        type: "Natte teelt",
        is_winterteelt: false,
        is_vanggewas: false,
        norms: {
            klei: { standard: 0, nv_area: 0 },
            zand_nwc: { standard: 0, nv_area: 0 },
            zand_zuid: { standard: 0, nv_area: 0 },
            loess: { standard: 0, nv_area: 0 },
            veen: { standard: 0, nv_area: 0 },
        },
    },
]
