import type { Table11Mestcodes } from "./types"

export const table11Mestcodes: Table11Mestcodes = [
  {
    p_type_rvo: "10",
    p_type_nitratesdirective: true,
    p_n_rt: 6.4,
    p_p_rt: 3.2,
  },
  {
    p_type_rvo: "11",
    p_type_nitratesdirective: true,
    p_n_rt: 4.0,
    p_p_rt: 1.3,
  },
  {
    p_type_rvo: "12",
    p_type_nitratesdirective: true,
    p_n_rt: 4.0,
    p_p_rt: 0.2,
  },
  {
    p_type_rvo: "13",
    p_type_nitratesdirective: true,
    p_n_rt: 9.2,
    p_p_rt: 9.2,
  },
  {
    p_type_rvo: "14",
    p_type_nitratesdirective: true,
    p_n_rt: 4.0,
    p_p_rt: 1.5,
  },
  {
    p_type_rvo: "17",
    p_type_nitratesdirective: true,
    p_n_rt: 4.2,
    p_p_rt: 5.0,
  },
  {
    p_type_rvo: "18",
    p_type_nitratesdirective: true,
    p_n_rt: 3.2,
    p_p_rt: 1.2,
  },
  {
    p_type_rvo: "19",
    p_type_nitratesdirective: true,
    p_n_rt: 5.5,
    p_p_rt: 2.2,
  },
  {
    p_type_rvo: "23",
    p_type_nitratesdirective: true,
    p_n_rt: 30.1,
    p_p_rt: 22.9,
  },
  {
    p_type_rvo: "30",
    p_type_nitratesdirective: true,
    p_n_rt: 9.9,
    p_p_rt: 6.2,
  },
  {
    p_type_rvo: "31",
    p_type_nitratesdirective: true,
    p_n_rt: 24.3,
    p_p_rt: 22.1,
  },
  {
    p_type_rvo: "32",
    p_type_nitratesdirective: true,
    p_n_rt: 26.0,
    p_p_rt: 20.9,
  },
  {
    p_type_rvo: "33",
    p_type_nitratesdirective: true,
    p_n_rt: 32.6,
    p_p_rt: 26.3,
  },
  {
    p_type_rvo: "35",
    p_type_nitratesdirective: true,
    p_n_rt: 26.8,
    p_p_rt: 24.9,
  },
  {
    p_type_rvo: "39",
    p_type_nitratesdirective: true,
    p_n_rt: 31.1,
    p_p_rt: 15.4,
  },
  {
    p_type_rvo: "40",
    p_type_nitratesdirective: true,
    p_n_rt: 8.1,
    p_p_rt: 8.0,
  },
  {
    p_type_rvo: "41",
    p_type_nitratesdirective: true,
    p_n_rt: 6.8,
    p_p_rt: 1.6,
  },
  {
    p_type_rvo: "42",
    p_type_nitratesdirective: true,
    p_n_rt: 2.0,
    p_p_rt: 0.9,
  },
  {
    p_type_rvo: "43",
    p_type_nitratesdirective: true,
    p_n_rt: 11.0,
    p_p_rt: 17.8,
  },
  {
    p_type_rvo: "46",
    p_type_nitratesdirective: true,
    p_n_rt: 3.8,
    p_p_rt: 2.4,
  },
  {
    p_type_rvo: "50",
    p_type_nitratesdirective: true,
    p_n_rt: 6.4,
    p_p_rt: 3.8,
  },
  {
    p_type_rvo: "56",
    p_type_nitratesdirective: true,
    p_n_rt: 8.5,
    p_p_rt: 4.7,
  },
  {
    p_type_rvo: "60",
    p_type_nitratesdirective: true,
    p_n_rt: 4.8,
    p_p_rt: 2.5,
  },
  {
    p_type_rvo: "61",
    p_type_nitratesdirective: true,
    p_n_rt: 9.1,
    p_p_rt: 4.8,
  },
  {
    p_type_rvo: "75",
    p_type_nitratesdirective: true,
    p_n_rt: 27.7,
    p_p_rt: 45.7,
  },
  {
    p_type_rvo: "76",
    p_type_nitratesdirective: true,
    p_n_rt: 7.9,
    p_p_rt: 3.1,
  },
  {
    p_type_rvo: "80",
    p_type_nitratesdirective: true,
    p_n_rt: 9.7,
    p_p_rt: 9.4,
  },
  {
    p_type_rvo: "81",
    p_type_nitratesdirective: true,
    p_n_rt: 5.8,
    p_p_rt: 3.8,
  },
  {
    p_type_rvo: "90",
    p_type_nitratesdirective: true,
    p_n_rt: 11.3,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "91",
    p_type_nitratesdirective: true,
    p_n_rt: 0.81,
    p_p_rt: 0.14,
  },
  {
    p_type_rvo: "92",
    p_type_nitratesdirective: true,
    p_n_rt: 4.4,
    p_p_rt: 3.0,
  },
  {
    p_type_rvo: "25",
    p_type_nitratesdirective: true,
    p_n_rt: 4.8,
    p_p_rt: 2.5,
  },
  {
    p_type_rvo: "26",
    p_type_nitratesdirective: true,
    p_n_rt: 5.0,
    p_p_rt: 3.0,
  },
  {
    p_type_rvo: "27",
    p_type_nitratesdirective: true,
    p_n_rt: 4.7,
    p_p_rt: 3.2,
  },
  {
    p_type_rvo: "95",
    p_type_nitratesdirective: true,
    p_n_rt: 7.1,
    p_p_rt: 5.3,
  },
  {
    p_type_rvo: "96",
    p_type_nitratesdirective: true,
    p_n_rt: 4.1,
    p_p_rt: 2.1,
  },
  {
    p_type_rvo: "97",
    p_type_nitratesdirective: true,
    p_n_rt: 8.9,
    p_p_rt: 8.1,
  },
  {
    p_type_rvo: "98",
    p_type_nitratesdirective: true,
    p_n_rt: 8.9,
    p_p_rt: 8.1,
  },
  {
    p_type_rvo: "99",
    p_type_nitratesdirective: true,
    p_n_rt: 32.6,
    p_p_rt: 17.7,
  },
  {
    p_type_rvo: "100",
    p_type_nitratesdirective: true,
    p_n_rt: 23.1,
    p_p_rt: 18.7,
  },
  {
    p_type_rvo: "101",
    p_type_nitratesdirective: true,
    p_n_rt: 23.1,
    p_p_rt: 18.7,
  },
  {
    p_type_rvo: "102",
    p_type_nitratesdirective: true,
    p_n_rt: 11.9,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "103",
    p_type_nitratesdirective: true,
    p_n_rt: 11.9,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "104",
    p_type_nitratesdirective: true,
    p_n_rt: 11.9,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "105",
    p_type_nitratesdirective: true,
    p_n_rt: 11.9,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "106",
    p_type_nitratesdirective: true,
    p_n_rt: 11.9,
    p_p_rt: 11.7,
  },
  {
    p_type_rvo: "107",
    p_type_nitratesdirective: true,
    p_n_rt: 5.5,
    p_p_rt: 3.1,
  },
  {
    p_type_rvo: "108",
    p_type_nitratesdirective: true,
  },
  {
    p_type_rvo: "109",
    p_type_nitratesdirective: true,
    p_n_rt: 8.0,
    p_p_rt: 4.4,
  },
  {
    p_type_rvo: "110",
    p_type_nitratesdirective: true,
    p_n_rt: 7.0,
    p_p_rt: 3.9,
  },
  {
    p_type_rvo: "111",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "112",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "113",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "114",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "115",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "116",
    p_type_nitratesdirective: false,
  },
  {
    p_type_rvo: "117",
    p_type_nitratesdirective: true,
    p_n_rt: 7.1,
    p_p_rt: 4.1,
  },
  {
    p_type_rvo: "120",
    p_type_nitratesdirective: true,
  },
  // Renure (RVO codes 130-134) is not legally recognized before 2026, so it
  // falls back to counting as regular animal manure against the 170 kg
  // dierlijke-mest norm for 2025 and earlier plans.
  {
    p_type_rvo: "130",
    p_type_nitratesdirective: true,
  },
  {
    p_type_rvo: "131",
    p_type_nitratesdirective: true,
  },
  {
    p_type_rvo: "132",
    p_type_nitratesdirective: true,
  },
  {
    p_type_rvo: "133",
    p_type_nitratesdirective: true,
  },
  {
    p_type_rvo: "134",
    p_type_nitratesdirective: true,
  },
]
