name: Tests
on: push

jobs:
  # Label of the container job for fdm-core
  test-core:
    name: core
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    permissions:
      contents: read
      packages: write
    # Docker Hub image that `container-job` executes in
    container: node:${{ matrix.node-version }}-bookworm-slim

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image with postgis extension
        image: postgis/postgis:17-3.5
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Include dependencies for codecov
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git curl gpg

      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10.29.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build fdm-data
        run: pnpm build
        working-directory: ./fdm-data

      - name: Build fdm-core
        run: pnpm build
        working-directory: ./fdm-core

      - name: Run tests with coverage
        run: pnpm test-coverage
        working-directory: ./fdm-core
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          # the default usernam
          POSTGRES_USER: postgres
          # the default password
          POSTGRES_PASSWORD: postgres
          # the default database
          POSTGRES_DB: postgres

      - name: fdm-core - Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./fdm-core/coverage/coverage-final.json
          flags: fdm-core
          token: ${{ secrets.CODECOV_TOKEN }}

  # Label of the container job for fdm-calculator
  test-calculator:
    name: calculator
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    permissions:
      contents: read
      packages: write
    # Docker Hub image that `container-job` executes in
    container: node:${{ matrix.node-version }}-bookworm-slim

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image with postgis extension
        image: postgis/postgis:17-3.5
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Include dependencies for codecov
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git curl gpg

      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10.29.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build fdm-data
        run: pnpm build
        working-directory: ./fdm-data

      - name: Build fdm-core
        run: pnpm build
        working-directory: ./fdm-core

      - name: Build fdm-calculator
        run: pnpm build
        working-directory: ./fdm-calculator

      - name: Run tests with coverage
        run: pnpm test-coverage
        working-directory: ./fdm-calculator
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          # the default usernam
          POSTGRES_USER: postgres
          # the default password
          POSTGRES_PASSWORD: postgres
          # the default database
          POSTGRES_DB: postgres

      - name: fdm-calculator - Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./fdm-calculator/coverage/coverage-final.json
          flags: fdm-calculator
          token: ${{ secrets.CODECOV_TOKEN }}

  # Label of the container job for fdm-data
  test-data:
    name: data
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    permissions:
      contents: read
      packages: write
    # Docker Hub image that `container-job` executes in
    container: node:${{ matrix.node-version }}-bookworm-slim

    steps:
      # Include dependencies for codecov
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git curl gpg

      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10.29.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build fdm-data
        run: pnpm build
        working-directory: ./fdm-data
      
      - name: Run tests with coverage
        run: pnpm test-coverage
        working-directory: ./fdm-data

      - name: fdm-data - Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./fdm-data/coverage/coverage-final.json
          flags: fdm-data
          token: ${{ secrets.CODECOV_TOKEN }}
